name: cross_vpn
description: cross platform solution vpn

publish_to: 'none'
version: 0.3.0+3

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  another_flushbar: ^1.10.29
  another_transformer_page_view: ^2.0.0
  font_awesome_flutter: ^10.0.0
  provider: ^6.0.1
  quiver: ^3.0.1
  sign_in_button: ^3.0.0
  get: ^4.6.5
  dio: ^4.0.4
  http_interceptor: ^1.0.2
  animations: ^2.0.3
  shared_preferences: ^2.0.12
  flutter_easyloading: ^3.0.5
  clipboard: ^0.1.3
  web_socket_channel: ^2.1.0
  json_annotation: ^4.4.0
  stack_trace: ^1.10.0
  url_launcher: ^6.0.12
  qr_flutter: ^4.0.0
  pointycastle: ^3.4.0
  json_rpc_2: ^3.0.0
  cryptography: ^2.0.5
  package_info_plus: ^3.0.2
  drawerbehavior: ^2.2.2
  device_info_plus: ^8.1.0
  flutter_svg: ^1.1.6
  firebase_core: ^2.1.1
  firebase_messaging: ^14.1.2
  google_mobile_ads: ^2.3.0

#  convert: ^3.0.0
#  js: ^0.6.3
  uuid: ^3.0.1
#  typed_data: ^1.1.6
#  stream_channel: ^2.0.0
  stream_transform: ^2.0.0
  build:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
